# This is a basic workflow to help you get started with Actions

name: CI
env:
  MARLIN_VERSION: 2.0.9.1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_firmware:
    name: Build Marlin firmware
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Marlin repo
      uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        path: tag/${{ env.MARLIN_VERSION }}
    
    - name: Debug output of folder structure
      run: |
        tree -d ${GITHUB_WORKSPACE}

    - name: Enable buildroot commands
      run: |
        chmod +x ${GITHUB_WORKSPACE}/tag/${MARLIN_VERSION}/buildroot/bin/*
        export PATH=${GITHUB_WORKSPACE}/tag/${MARLIN_VERSION}/buildroot/bin:$PATH

    - name: Select Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Configure build
      run: |
        use_example_configs Creality/Ender-2

