# This is a basic workflow to help you get started with Actions

name: CI
env:
  MARLIN_VERSION: "2.0.9.1"
  PRINTER_MODEL: "Creality/Ender-2"
  TARGET_ENV: "melzi_optiboot_optimized"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_firmware:
    name: Build Marlin firmware
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Marlin repo
      uses: actions/checkout@v2
      with:
        repository: MarlinFirmware/Marlin
        path: tag/${{ env.MARLIN_VERSION }}
    
    - name: Debug output of folder structure
      run: |
        tree -d ${GITHUB_WORKSPACE}

    - name: Enable buildroot commands
      env:
        BUILDROOT_BIN: "${{ github.workspace }}/tag/${{ env.MARLIN_VERSION }}/buildroot/bin"
      run: |
        chmod +x ${BUILDROOT_BIN}/*
        echo "${BUILDROOT_BIN}" >> $GITHUB_PATH

    - name: Select Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Install PlatformIO
      run: |
        pip install platformio
        platformio update

    - name: Configure build
      run: |
        cd "${GITHUB_WORKSPACE}/tag/${MARLIN_VERSION}"
        # use Ender 2 example from Marlin team as base configuration
        use_example_configs ${MARLIN_VERSION} ${PRINTER_MODEL}
    
    - name: Build
      run: |
        platformio run -e ${TARGET_ENV}
        
